kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/jenkins/"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-install
data:
  docker-install.sh: |
    #!/bin/bash
    apt-get update
    apt-get install docker.io -y

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jenkins
    tier: jenkins
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
        tier: jenkins
    spec:
      serviceAccount: jenkins
      initContainers:
      - image: 127.0.0.1:30400/jenkins-init:latest
        name: kubectl-config
        command:
        - sh
        - kubectl-config-context.sh
        volumeMounts:
        - name: kube-config
          mountPath: "/.kube"
      containers:
      - image: 127.0.0.1:30400/jenkins:latest
        name: jenkins
        securityContext:
          privileged: true
        volumeMounts:
        - name: kube-config
          mountPath: "/.kube"
        - name: docker
          mountPath: /var/run/docker.sock
        - name: jenkins-persistent-storage
          mountPath: /root/.jenkins
        ports:
        - containerPort: 8080
          name: jenkins
      volumes:
      - name: kube-config
        emptyDir: {}
      - name: docker
        hostPath:
          path: /var/run/docker.sock
      - name: jenkins-persistent-storage
        persistentVolumeClaim:
          claimName: jenkins-claim